on:
  push:
   branches: 
   - main

jobs:
    cypress_job:
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
           node-version: 18.18

        # TODO: Add npm cache  
        - name: Install dependencies
          run: npm ci

        - name: Run Cypress tests
          run: npm run cy:run

        - name: Archive test report artifacts
          uses: actions/upload-artifact@v3
          with:
            name: html-report
            path: cypress/reports/html
